spring:
  data:
    mongodb:
      database: test
      uri: mongodb://localhost:27017
      repositories:
        type: auto
    jpa:

      repositories:
        enabled: true
  jpa:
    properties:
      hibernate:

    show-sql: true
    open-in-view: false

  mvc:
    throw-exception-if-no-handler-found: true

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/milove

  web:
    resources:
      add-mappings: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false

okta:
  oauth2:
    issuer: https://dev-i1ehhh4j3rf2tyqz.us.auth0.com/
    audience: https://miloverada-api

server:
  port: 6060
  tomcat:
    max-http-form-post-size: 50000000
logging:
  file:
    path: logs
