spring:
  data:
    mongodb:
      database: test
      uri: mongodb://eu-life-rootinfo:uSVtE7VF7VGbQv5@ac-u9efhpg-shard-00-00.jhfxdna.mongodb.net:27017,ac-u9efhpg-shard-00-01.jhfxdna.mongodb.net:27017,ac-u9efhpg-shard-00-02.jhfxdna.mongodb.net:27017/?ssl=true&replicaSet=atlas-14ato7-shard-0&authSource=admin&retryWrites=true&w=majority
      repositories:
        type: auto
    jpa:

      repositories:
        enabled: true
  jpa:
    properties:
      hibernate:

    show-sql: true
#    open-in-view: false

  mvc:
    throw-exception-if-no-handler-found: true

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
    url: jdbc:postgresql://127.0.0.1:5432/milove

  web:
    resources:
      add-mappings: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false

okta:
  oauth2:
    issuer: https://dev-i1ehhh4j3rf2tyqz.us.auth0.com/
    audience: https://miloverada-api

server:
  port: 8443

  tomcat:
    max-http-form-post-size: 50000000
  ssl:
    enabled: true
    key-store: /etc/letsencrypt/live/api.miloverada.gov.ua/keystore.p12
    key-store-password: komunist
    key-store-type: PKCS12
    key-alias: tomcat

logging:
  file:
    path: logs
