

spring:
  jpa:
    properties:
      hibernate:
        format_sql=true
    show-sql: true

  mvc:

    throw-exception-if-no-handler-found: true


  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: komunist
    url: jdbc:postgresql://localhost:5432/postgres

  web:
    resources:
      add-mappings: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


okta:
  oauth2:
    issuer: https://dev-lxs2cvzdocbe1ne6.eu.auth0.com/
    audience: https://miloverada-api

server:
  port: 6060

  error:
    whitelabel:
      enabled: false
    include-message: always
#logging:
#  level:
#    web: debug
