
name: remoteDeploy

on:
  push:
    branches:
      - main


# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest

    # steps:
    #   - name: checkout
    #     uses: actions/checkout@v1

    #   - name: ssh scp ssh pipelines
    #     uses: cross-the-world/ssh-scp-ssh-pipelines@latest
    #     env:
    #       WELCOME: "ssh scp ssh pipelines"
    #       LASTSSH: "Doing something after copying"
    #     with:
    #       host: 34.116.131.99
    #       user: makcimkakakakaka
    #       key: |-
    #         -----BEGIN OPENSSH PRIVATE KEY-----
    #         b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAaAAAABNlY2RzYS
    #         1zaGEyLW5pc3RwMjU2AAAACG5pc3RwMjU2AAAAQQRoMDOh+kDVkq29aDbb5Lf2uRtk2dwF
    #         TTKdnKuf4k7+Llp8hJ1YXiqxj9eSC0hHGBNqT3DFv6emygZ9Qz5kAs9DAAAAqC4YtX4uGL
    #         V+AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGgwM6H6QNWSrb1o
    #         Ntvkt/a5G2TZ3AVNMp2cq5/iTv4uWnyEnVheKrGP15ILSEcYE2pPcMW/p6bKBn1DPmQCz0
    #         MAAAAgRt7P2s7Wo9Q9DxxwInQeevOdgVEH43JbgzgHTKIy+DkAAAAPcm9vdEBtaWxvdmVy
    #         YWRhAQ==
    #         -----END OPENSSH PRIVATE KEY-----
    #       connect_timeout: 10s
    #       first_ssh: |-
    #         sudo systemctl stop app.service
    #         rm -r milove-otg.gov.ua
    #         git clone https://github.com/LiashenkoAndrey/milove-otg.gov.ua.git;
    #         sudo systemctl start app.service


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: fifsky/ssh-action@master
        with:
          command: |
            ls
            sudo systemctl stop app.service
            rm -r milove-otg.gov.ua
            git clone https://github.com/LiashenkoAndrey/milove-otg.gov.ua.git;
            sudo systemctl start app.service
          host: 34.116.131.99
          user: makcimkakakakaka
          key: |-
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
            NhAAAAAwEAAQAAAYEA3Bw9jg7Bgr2Gg4Nuus5WVIhwZuzwIn5s2g+WbwJQpFnJJJbkb0uk
            01bVpzBF0QreYGP5Z4/NdTSNMZ37q77SMNtflqN6W8bGC4/LWIB9fl0LF7K0l+zDIbesxD
            YAYl8lqobZhOGcwtzbyN7UtoQOGMU1xB0oeSKl4PxCkXJ91/qOxeAMsuZAh8kpZgrvCRHz
            mFVWcW41yCA4lCIeWD1v4coRmyWYd+re+ODXdZapPEBcgTy0CPXNr6xAvBsNmcL9x1ZTPj
            ymIXPc8NgMZfeUeR7SdfTDec0JTXVcUoJrAFiDDlwBKpRVT/A218r0ylvacUWpeI3EIgSY
            spSf3GQ9zT2Nq5+hQ9jSntEA5RA9+j1PahzzeIysmKqu8FMe4WsjruthIX/e+xgi5YBQ+t
            qC1Q+qkkBIVe2IvF+zJQqp7yMZZGTlaUCVW1FdJ019ubjqccrMGL+5fG30T0FnW4RoskXK
            o10yQ8FnCmtOy/uQInQmApmU1UYAANoqBe7mur6dAAAFmHgCnht4Ap4bAAAAB3NzaC1yc2
            EAAAGBANwcPY4OwYK9hoODbrrOVlSIcGbs8CJ+bNoPlm8CUKRZySSW5G9LpNNW1acwRdEK
            3mBj+WePzXU0jTGd+6u+0jDbX5ajelvGxguPy1iAfX5dCxeytJfswyG3rMQ2AGJfJaqG2Y
            ThnMLc28je1LaEDhjFNcQdKHkipeD8QpFyfdf6jsXgDLLmQIfJKWYK7wkR85hVVnFuNcgg
            OJQiHlg9b+HKEZslmHfq3vjg13WWqTxAXIE8tAj1za+sQLwbDZnC/cdWUz48piFz3PDYDG
            X3lHke0nX0w3nNCU11XFKCawBYgw5cASqUVU/wNtfK9Mpb2nFFqXiNxCIEmLKUn9xkPc09
            jaufoUPY0p7RAOUQPfo9T2oc83iMrJiqrvBTHuFrI67rYSF/3vsYIuWAUPragtUPqpJASF
            XtiLxfsyUKqe8jGWRk5WlAlVtRXSdNfbm46nHKzBi/uXxt9E9BZ1uEaLJFyqNdMkPBZwpr
            Tsv7kCJ0JgKZlNVGAADaKgXu5rq+nQAAAAMBAAEAAAGBAIwYiXFOoQpG+UPhtuu9gyNAyF
            IqgtlhoITWoQg87/j7kNPyGqlf+yPsxAYq6nUYNtwhJdAtrjboYOnwxQvWY9BnAJtPqASc
            KteXCXVmKvnv3KyTuPBt6PEgCB3GxU3Xg5DbTb2PIAjDLDzY34jf2l0XwJX3fRhE3lGqHf
            CXb9O1DYSSi2KevPnwJqJlWSlrvKD7yA5geGjNYVWftbKyP/D1fWlDb5z76Dl+WoTkhQjt
            ajNz4J9HXEhxGa7ghTKV8WQ9pALOQRfZuk0RQXjhb3nubiBFnSn6qE8D+tPpjdySMezZRE
            NnWJDyFhy/JV+sHaEdF5Kj9zmNYQy1zZNw6K1MydqoQH90c3aYD0UHz1nzfTd7muCO4QsY
            8LM2E0RAbHgicHnO5j3cYzrpp5/MDWkqgAbaNQlQSNwJ15SOm9FzofzY1xy34ezR0I6a39
            PRamFBWSlvhOB4yvgz3KDLyL16ilnJemI5zUdYQrVpx5194YCRnHSSSt+XK3kwj8PLvQAA
            AMEAueIpH/lUdI4gUuKwLfKtFE4MWQQHMgDqhUuOQhI+BdGyxO5cNNNt/bqdLUnpUck+4P
            JC+V54s93I8AqZE4sPB8PKCDmz1Hv5x8eXT3mKOijU4bF7sibUNI5sZ8R66kmZNMpP4bTW
            4Tbci42T1+5rXOf//ftPmfBp5e9kRSecYIJYuZ4efvMedleTTBlA73fCvTPsMVQLhjG+vh
            akG15MSa2ztL71aWn7zZXq2USZeZzs57ZzoNcbHS7pPfT2ztsKAAAAwQD9+6TVIvfhzRPe
            AJv+gZ3WQRRGGMo0+NFJzW0oUlZ9pxcvzdtjlCCwqY5QO1mCcG5kp1SYhm0DG3pgd+XotT
            WvqwqvoKZIWSPWLc/2zcRSJa0DHD+uDZV6oVS6PeJ18t6nmw4jKojLuaZUKjkJydzV3+sW
            M4DRMvUt7TZg3GZ48h3kLDDLS7+APjLTRpO6vjm1/2AQsIrWyk+niLzPblcAhlqUEEQY6B
            Ywlq1dSvvPaXGdP0To+OOLfkSvKIiDOC8AAADBAN3bu3YqK/+sLEaygJMjv2SqnrFa8v43
            OmQxJnFoSrm+QEuOdChAvPbAVWcLbGAokJz5Ap7EztqWfv/G2m842oC0CC7RO6Ia377wAT
            6KIWry2N0jaXZxdLi/qiDt8vMdlRKDwZDCBpZb+2i1evflz0Ys/1JBGwk9oOpC3X9/mOJ5
            D5QpiOFMtasI3vkxtLcGiK2hthDIPZ2bkfFknl306BtyV/UCiNHjrz7zE6jUkuFnH9rnTr
            mlgiCqahvA4bW28wAAABttYWtjaW1rYWtha2FrYWthQG1pbG92ZXJhZGEBAgMEBQY=
            -----END OPENSSH PRIVATE KEY-----
      
